Traceback (most recent call last):
  File "/Users/brunamoura/PrevisorReconhecimento/.venv/lib/python3.9/site-packages/jupyter_cache/executors/utils.py", line 58, in single_nb_execution
    executenb(
  File "/Users/brunamoura/PrevisorReconhecimento/.venv/lib/python3.9/site-packages/nbclient/client.py", line 1314, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
  File "/Users/brunamoura/PrevisorReconhecimento/.venv/lib/python3.9/site-packages/jupyter_core/utils/__init__.py", line 165, in wrapped
    return loop.run_until_complete(inner)
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.9/lib/python3.9/asyncio/base_events.py", line 642, in run_until_complete
    return future.result()
  File "/Users/brunamoura/PrevisorReconhecimento/.venv/lib/python3.9/site-packages/nbclient/client.py", line 709, in async_execute
    await self.async_execute_cell(
  File "/Users/brunamoura/PrevisorReconhecimento/.venv/lib/python3.9/site-packages/nbclient/client.py", line 1062, in async_execute_cell
    await self._check_raise_for_error(cell, cell_index, exec_reply)
  File "/Users/brunamoura/PrevisorReconhecimento/.venv/lib/python3.9/site-packages/nbclient/client.py", line 918, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
# Importar bibliotecas
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

from sklearn.model_selection import train_test_split, StratifiedKFold
from sklearn.metrics import classification_report, confusion_matrix, ConfusionMatrixDisplay
from sklearn.metrics import roc_curve, auc, precision_recall_curve, roc_auc_score
from sklearn.preprocessing import RobustScaler
from sklearn.pipeline import Pipeline
from sklearn import metrics
from sklearn.metrics import make_scorer, recall_score
from sklearn.feature_selection import SelectFromModel

from xgboost import XGBClassifier

from skopt import BayesSearchCV
from skopt.space import Real, Integer

#Estilizar conteÃºdo
import warnings
warnings.simplefilter(action='ignore', category=FutureWarning)
pd.set_option('display.max_rows', None)
pd.set_option('display.max_columns', None)
pd.set_option('display.float_format', '{:.2f}'.format)

def estilo_tabelas(df, max_altura='300px', casas_decimais=3):
    return (
        df.style.set_table_styles(
            [
                {'selector': 'thead th', 'props': [('font-size', '12px'), ('text-align', 'center'), ('border-bottom', '2px solid #007BFF')]},
                {'selector': 'td', 'props': [('font-size', '10px'), ('text-align', 'center'), ('max-height', '40px'), ('white-space', 'nowrap'), ('text-overflow', 'ellipsis'), ('overflow', 'hidden'), ('max-width', '100px')]},
                {'selector': 'tr:nth-child(odd)', 'props': [('background-color', '#ffffff')]},
                {'selector': 'table', 'props': [('width', '90%'), ('margin-left', 'auto'), ('margin-right', 'auto'), ('border-collapse', 'collapse')]},
                {'selector': 'td, th', 'props': [('border', '1px solid #666')]},  # Bordas cinza escuro
            ]
        ).set_properties(
            **{'border-color': 'darkgray', 'border-style': 'solid', 'border-width': '1px'}
        ).set_table_attributes(
            f'style="height:auto; overflow:auto; max-height:{max_altura}; display:block;"'  
        ).format(
            precision=casas_decimais  
        )
    )

# FunÃ§Ã£o para plotar as curvas ROC e PR
def plot_roc_pr_curves(y_test, y_pred_proba, model_name):
    # Curva ROC
    fpr, tpr, _ = roc_curve(y_test, y_pred_proba)
    roc_auc = auc(fpr, tpr)

    plt.figure()
    plt.plot(fpr, tpr, label=f'{model_name} (AUC = {roc_auc:.2f})')
    plt.plot([0, 1], [0, 1], 'k--')
    plt.title(f'Curva ROC - {model_name}')
    plt.xlabel('Taxa de Falsos Positivos')
    plt.ylabel('Taxa de Verdadeiros Positivos')
    plt.legend(loc='lower right')
    plt.show()

    # Curva de PrecisÃ£o-RevocaÃ§Ã£o
    precision, recall, _ = precision_recall_curve(y_test, y_pred_proba)
    pr_auc = auc(recall, precision)

    plt.figure()
    plt.plot(recall, precision, label=f'{model_name} (AUC = {pr_auc:.2f})')
    plt.title(f'Curva de PrecisÃ£o-RevocaÃ§Ã£o - {model_name}')
    plt.xlabel('RevocaÃ§Ã£o')
    plt.ylabel('PrecisÃ£o')
    plt.legend(loc='lower left')
    plt.show()

# Importar a base de dados

df_eventos_2018_2024_modelo2 = pd.read_csv(
    "https://raw.githubusercontent.com/brunagmoura/PrevisorReconhecimento/refs/heads/main/df_eventos_2018_2024_modelo2.csv",
    sep=';',
    decimal=',',
)

estilo_tabelas(df_eventos_2018_2024_modelo2.head(5))
------------------


[0;31m---------------------------------------------------------------------------[0m
[0;31mXGBoostError[0m                              Traceback (most recent call last)
Cell [0;32mIn[1], line 16[0m
[1;32m     13[0m [38;5;28;01mfrom[39;00m [38;5;21;01msklearn[39;00m[38;5;21;01m.[39;00m[38;5;21;01mmetrics[39;00m [38;5;28;01mimport[39;00m make_scorer, recall_score
[1;32m     14[0m [38;5;28;01mfrom[39;00m [38;5;21;01msklearn[39;00m[38;5;21;01m.[39;00m[38;5;21;01mfeature_selection[39;00m [38;5;28;01mimport[39;00m SelectFromModel
[0;32m---> 16[0m [38;5;28;01mfrom[39;00m [38;5;21;01mxgboost[39;00m [38;5;28;01mimport[39;00m XGBClassifier
[1;32m     18[0m [38;5;28;01mfrom[39;00m [38;5;21;01mskopt[39;00m [38;5;28;01mimport[39;00m BayesSearchCV
[1;32m     19[0m [38;5;28;01mfrom[39;00m [38;5;21;01mskopt[39;00m[38;5;21;01m.[39;00m[38;5;21;01mspace[39;00m [38;5;28;01mimport[39;00m Real, Integer

File [0;32m~/PrevisorReconhecimento/.venv/lib/python3.9/site-packages/xgboost/__init__.py:6[0m
[1;32m      1[0m [38;5;124;03m"""XGBoost: eXtreme Gradient Boosting library.[39;00m
[1;32m      2[0m 
[1;32m      3[0m [38;5;124;03mContributors: https://github.com/dmlc/xgboost/blob/master/CONTRIBUTORS.md[39;00m
[1;32m      4[0m [38;5;124;03m"""[39;00m
[0;32m----> 6[0m [38;5;28;01mfrom[39;00m [38;5;21;01m.[39;00m [38;5;28;01mimport[39;00m tracker  [38;5;66;03m# noqa[39;00m
[1;32m      7[0m [38;5;28;01mfrom[39;00m [38;5;21;01m.[39;00m [38;5;28;01mimport[39;00m collective, dask
[1;32m      8[0m [38;5;28;01mfrom[39;00m [38;5;21;01m.[39;00m[38;5;21;01mcore[39;00m [38;5;28;01mimport[39;00m (
[1;32m      9[0m     Booster,
[1;32m     10[0m     DataIter,
[0;32m   (...)[0m
[1;32m     15[0m     build_info,
[1;32m     16[0m )

File [0;32m~/PrevisorReconhecimento/.venv/lib/python3.9/site-packages/xgboost/tracker.py:9[0m
[1;32m      6[0m [38;5;28;01mfrom[39;00m [38;5;21;01menum[39;00m [38;5;28;01mimport[39;00m IntEnum, unique
[1;32m      7[0m [38;5;28;01mfrom[39;00m [38;5;21;01mtyping[39;00m [38;5;28;01mimport[39;00m Dict, Optional, Union
[0;32m----> 9[0m [38;5;28;01mfrom[39;00m [38;5;21;01m.[39;00m[38;5;21;01mcore[39;00m [38;5;28;01mimport[39;00m _LIB, _check_call, make_jcargs
[1;32m     12[0m [38;5;28;01mdef[39;00m [38;5;21mget_family[39m(addr: [38;5;28mstr[39m) [38;5;241m-[39m[38;5;241m>[39m [38;5;28mint[39m:
[1;32m     13[0m [38;5;250m    [39m[38;5;124;03m"""Get network family from address."""[39;00m

File [0;32m~/PrevisorReconhecimento/.venv/lib/python3.9/site-packages/xgboost/core.py:269[0m
[1;32m    265[0m     [38;5;28;01mreturn[39;00m lib
[1;32m    268[0m [38;5;66;03m# load the XGBoost library globally[39;00m
[0;32m--> 269[0m _LIB [38;5;241m=[39m [43m_load_lib[49m[43m([49m[43m)[49m
[1;32m    272[0m [38;5;28;01mdef[39;00m [38;5;21m_check_call[39m(ret: [38;5;28mint[39m) [38;5;241m-[39m[38;5;241m>[39m [38;5;28;01mNone[39;00m:
[1;32m    273[0m [38;5;250m    [39m[38;5;124;03m"""Check the return value of C API call[39;00m
[1;32m    274[0m 
[1;32m    275[0m [38;5;124;03m    This function will raise exception when error occurs.[39;00m
[0;32m   (...)[0m
[1;32m    281[0m [38;5;124;03m        return value from API calls[39;00m
[1;32m    282[0m [38;5;124;03m    """[39;00m

File [0;32m~/PrevisorReconhecimento/.venv/lib/python3.9/site-packages/xgboost/core.py:222[0m, in [0;36m_load_lib[0;34m()[0m
[1;32m    220[0m     [38;5;28;01mif[39;00m [38;5;129;01mnot[39;00m lib_success:
[1;32m    221[0m         libname [38;5;241m=[39m os[38;5;241m.[39mpath[38;5;241m.[39mbasename(lib_paths[[38;5;241m0[39m])
[0;32m--> 222[0m         [38;5;28;01mraise[39;00m XGBoostError(
[1;32m    223[0m             [38;5;124mf[39m[38;5;124m"""[39m
[1;32m    224[0m [38;5;124mXGBoost Library ([39m[38;5;132;01m{[39;00mlibname[38;5;132;01m}[39;00m[38;5;124m) could not be loaded.[39m
[1;32m    225[0m [38;5;124mLikely causes:[39m
[1;32m    226[0m [38;5;124m  * OpenMP runtime is not installed[39m
[1;32m    227[0m [38;5;124m    - vcomp140.dll or libgomp-1.dll for Windows[39m
[1;32m    228[0m [38;5;124m    - libomp.dylib for Mac OSX[39m
[1;32m    229[0m [38;5;124m    - libgomp.so for Linux and other UNIX-like OSes[39m
[1;32m    230[0m [38;5;124m    Mac OSX users: Run `brew install libomp` to install OpenMP runtime.[39m
[1;32m    231[0m 
[1;32m    232[0m [38;5;124m  * You are running 32-bit Python on a 64-bit OS[39m
[1;32m    233[0m 
[1;32m    234[0m [38;5;124mError message(s): [39m[38;5;132;01m{[39;00mos_error_list[38;5;132;01m}[39;00m
[1;32m    235[0m [38;5;124m"""[39m
[1;32m    236[0m         )
[1;32m    237[0m     _register_log_callback(lib)
[1;32m    239[0m     [38;5;28;01mdef[39;00m [38;5;21mparse[39m(ver: [38;5;28mstr[39m) [38;5;241m-[39m[38;5;241m>[39m Tuple[[38;5;28mint[39m, [38;5;28mint[39m, [38;5;28mint[39m]:

[0;31mXGBoostError[0m: 
XGBoost Library (libxgboost.dylib) could not be loaded.
Likely causes:
  * OpenMP runtime is not installed
    - vcomp140.dll or libgomp-1.dll for Windows
    - libomp.dylib for Mac OSX
    - libgomp.so for Linux and other UNIX-like OSes
    Mac OSX users: Run `brew install libomp` to install OpenMP runtime.

  * You are running 32-bit Python on a 64-bit OS

Error message(s): ["dlopen(/Users/brunamoura/PrevisorReconhecimento/.venv/lib/python3.9/site-packages/xgboost/lib/libxgboost.dylib, 0x0006): Library not loaded: @rpath/libomp.dylib\n  Referenced from: <F2F42313-BF4F-3B95-A853-AE1DE94D4C87> /Users/brunamoura/PrevisorReconhecimento/.venv/lib/python3.9/site-packages/xgboost/lib/libxgboost.dylib\n  Reason: tried: '/opt/homebrew/opt/libomp/lib/libomp.dylib' (no such file), '/System/Volumes/Preboot/Cryptexes/OS/opt/homebrew/opt/libomp/lib/libomp.dylib' (no such file), '/opt/homebrew/opt/libomp/lib/libomp.dylib' (no such file), '/System/Volumes/Preboot/Cryptexes/OS/opt/homebrew/opt/libomp/lib/libomp.dylib' (no such file)"]


